name: com.example.simple_app
description: A simple Flutter application demonstrating a login flow using the Cubit pattern.
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.0.0
  mocktail: ^0.1.5

flutter:
  uses-material-design: true